### ISSUE TITLE
🎉 UI Overhaul!

### ISSUE THREAD

**Issue by sharonjoji99** [adi-kiran/burnout-healthgoalsapp#1]
## Why we need this!
The current design is very wonky, with no clear routes for navigating through the app. Multiple unnecessary clicks are required to achieve simple tasks.

## Affected parts
- Home Screen
- Source code organization
- Use of vanilla HTML/CSS

## Solutions
- Adopt any simple frameworks to divide the project's UI into modules, allowing for better modularity.
- Make the application simple to use, with lesser pages and focusing on what the product is aimed at E.g. make landing page for entering and tracking calories since this is a calorie tracker.
- Use pages that can dynamically render, thereby requiring no refreshes and no new pages for showing updated data.
- Use good color palette for entire website.

**Comment by sharonjoji99** [comment]
Looks like this issue has been completed as part of several other minor issues.

**Comment by sharonjoji99** [comment]
Do we want to make any more UI changes or can close this issues ? @Diksha-Maurya @amritav

**Comment by Diksha-Maurya** [comment]
> Do we want to make any more UI changes or can close this issues ? @Diksha-Maurya @amritav

We can suggest the user the diet plan according to the goal/currect weight.

**Comment by sharonjoji99** [comment]
Cool,  i will close this issue then. 🚀
