### ISSUE TITLE
🤖 Kill the bot! 

### ISSUE THREAD

**Issue by sharonjoji99** [adi-kiran/burnout-healthgoalsapp#2]
## Why this change
The configured bot uses connection to dialogue flow which we are not able to get access to, retraining with new data whoever will be very tedious. Moreover, the bot does not help in making the primary objective of the application stronger and hence can be removed.

## Changes Required
Remove all references, to bot from the source code

**Comment by amritav** [comment]
Wait why are we killing the bot?

**Comment by sharonjoji99** [comment]
So, turns out, they created an account with diaglogueFlow and used some dataset to train that chat bot. We no longer have access to the bot.

**Comment by adi-kiran** [comment]
Yeah, the bot doesn't add much value to our app right now.

**Comment by sharonjoji99** [comment]
Will exlcude this as part of the UI redesign
