### ISSUE TITLE
Profile change should fetch data from the Database

### ISSUE THREAD

**Issue by sharonjoji99** [adi-kiran/burnout-healthgoalsapp#39]
## What is broken
In the forked repo, the data was not being fetched from database. Hardcoded values were being used.

## What is the fix
Creates API endpoints to retrieve data from the database and render them dynamically on the webpage

## Additional comments
none

**Comment by amritav** [comment]
Wait what?? It wasn't already?

**Comment by sharonjoji99** [comment]
duplicate
