### ISSUE TITLE
Add a "Contact Us" Page

### ISSUE THREAD

**Issue by amritav** [adi-kiran/burnout-healthgoalsapp#4]
### Why we need this
Currently there is no recourse for the user or future contributors of this project to reach out to the development team. A contact us page is essential because it:
1. Facilitates user engagement and feedback.
2. Provides support and assistance to users.
3. Builds trust and professionalism.
4. Can be essential for collaboration and partnerships.
5. Enhances accessibility and user experience.

### Scope of Impact
Footers of every existing page in the website
A new "Contact Us Page"

### Implementation

- Create a wireframe or design for the page layout, considering the placement of contact details and any additional elements.
- Develop the HTML/CSS for the "Contact Us" page. 
- Update the footer template or component of your website to include a link or button that leads to the "Contact Us" page. 
- Ensure that the "Contact Us" page and footer elements are responsive.
- Thoroughly test the "Contact Us" page and form to make sure it functions correctly. Test it on different browsers.
- Ensure that the "Contact Us" page and footer elements are accessible to users with disabilities, following any web accessibility standards.
- (Optional) Implement confirmation messages or email notifications to acknowledge user submissions.

### Points to consider
When creating a "Contact Us" page, it's essential to make it user-friendly and provide clear instructions on how to get in touch.

**Comment by amritav** [comment]
@Diksha-Maurya @sharonjoji99  Does this UI look good?
![MicrosoftTeams-image](https://github.com/adi-kiran/burnout-healthgoalsapp/assets/19224584/674c2dd6-ecd6-4a5d-81f4-eae7586c2ca0)

**Comment by Diksha-Maurya** [comment]
> @Diksha-Maurya @sharonjoji99 Does this UI look good? ![MicrosoftTeams-image](https://user-images.githubusercontent.com/19224584/276466718-674c2dd6-ecd6-4a5d-81f4-eae7586c2ca0.png)

Ui looks good but wouldn't a form be better?

**Comment by sharonjoji99** [comment]
I guess we could pick this up later as this not a priority, @amritav i think you can merge and close this.

**Comment by amritav** [comment]
Will do.
