### ISSUE TITLE
Implement Search Box for Events Page

### ISSUE THREAD

**Issue by amritav** [adi-kiran/burnout-healthgoalsapp#40]
#### **Background:**

Our website's events page is steadily growing with a variety of events being listed. To enhance user experience and help users quickly find events of their interest, it's beneficial to introduce a search functionality.

#### **Feature:**

- **Search Box Integration**: Add a search box at the top or a prominent position on the events page.
- **Search Functionality**: Allow users to type keywords or phrases to filter through the listed events.
- **Live Search**: (Optional) As users type, display matching events in real-time below the search box.

#### **Benefits:**

1. **User Experience**: Provides a faster and more direct way for users to find events.
2. **Efficiency**: Reduces the need to manually scroll through numerous events.
3. **Engagement**: Users are more likely to engage with events that match their interests, boosting participation and interaction.

#### **Dependencies & Concerns:**

- Determine if the search will be purely frontend-based (filtering already loaded events) or if it will query the backend database.

**Comment by sharonjoji99** [comment]
Not a priority but would be cool to get this working!

**Comment by sharonjoji99** [comment]
I guess we can do the search from the front end in react instead of querying the database and then returning the results and then rendering.

**Comment by amritav** [comment]
Since we don't have pagination, wouldn't we have too much data to render? Doesn't seem very scalable.

**Comment by sharonjoji99** [comment]
Ahh right, sounds like a good plan for future scope :)

**Comment by amritav** [comment]
Implemented search. Closing this issue.
