### ISSUE TITLE
Profile pages requires two clicks to save the data.

### ISSUE THREAD

**Issue by sharonjoji99** [adi-kiran/burnout-healthgoalsapp#41]
## What is broken
When opening the profile page the data which we edit for the logged in user does not get saved immediately. Multiple clicks are required to save the data into the database.

## Steps to reproduce
- "npm start" and "flask run"
-  Login in as any user
-  Open profile
-  Edit the values

## What is the fix?
- Seems to be an issue with how we handle the states in the component.

**Comment by sharonjoji99** [comment]
Not sure why , but only when i click SAVE twice does it save!. Help Needed !

**Comment by amritav** [comment]
Cool, let me look into it.

**Comment by amritav** [comment]
Just took a quick look at the code. I think it could have something to do with the editable target, calories and goals? Might need to take a deeper look.

**Comment by sharonjoji99** [comment]
Oh right, understood will raise a PR soon.

**Comment by sharonjoji99** [comment]
Merged with main, closing this
