### ISSUE TITLE
Populate Events Page via Backend Instead of Hardcoding

### ISSUE THREAD

**Issue by amritav** [adi-kiran/burnout-healthgoalsapp#42]
#### **Background:**

The current implementation of the events page involves hardcoded event listings. As our platform grows and the number of events increases, this method becomes unsustainable and inefficient. To streamline the management of events and allow for dynamic updates, we should transition to populating the events page via the backend.

#### **Feature:**

- **Backend Integration**: Fetch event data from the backend to display on the events page.
- **Dynamic Loading**: Events should load dynamically.

#### **Benefits:**

1. **Scalability**: Easier management of events as the platform scales.
2. **Centralized Management**: Event data can be managed from a central location (MongoDB database), reducing redundancy and potential inconsistencies.

**Comment by amritav** [comment]
The current code has static HTML pages for each event. The solution doesn't seem scalable.

**Comment by sharonjoji99** [comment]
The story of every page🥲

Just an idea , maybe use modals which could be reused instead of redirecting them to a whole new page to view event details.

**Comment by sharonjoji99** [comment]
Lets use the matieral Modal itself maybe : https://mui.com/material-ui/react-modal/

**Comment by Diksha-Maurya** [comment]
> Lets use the matieral UI Modal itself maybe : https://mui.com/material-ui/react-modal/

+1 to the above idea

**Comment by amritav** [comment]
@Diksha-Maurya @sharonjoji99 Thanks!! Will do

**Comment by amritav** [comment]
Accidentally closed the issue.
