### ISSUE TITLE
Use JWT Token for authorization

### ISSUE THREAD

**Issue by sharonjoji99** [adi-kiran/burnout-healthgoalsapp#43]
## How it is currently
No package was being used for authentication, the username and password was being checked against the database and redirected to the home page. Users can access Api endpoints without being authenticated.
 
## Why we need this change
By using concept of access token, we can define the time for which a user can be logged in. The token created will be stored in the user's browser and sent along with each subsequent request. Once the token has expired the user is expected to login again.
 
## Changes required
- Use JWT to create, authenticate, and logout user.

**Comment by sharonjoji99** [comment]
Will be proceeding with saving the token in localstorage. is that okay?

**Comment by Diksha-Maurya** [comment]
> Will be proceeding with saving the token in localstorage. is that okay?

Why localstorage and not session storage ?

**Comment by sharonjoji99** [comment]
localstorage will let users remaing logged in even if they are on a new tab.

**Comment by Diksha-Maurya** [comment]
> localstorage will let users remaing logged in even if they are on a new tab.

okay.. cool. Thanks

**Comment by sharonjoji99** [comment]
Implementation complete, although the logout button is a little finicky, may require someone to look into.
