### ISSUE TITLE
Bug: Users Can Enroll Multiple Times in an Event

### ISSUE THREAD

**Issue by amritav** [adi-kiran/burnout-healthgoalsapp#44]
### Bug Description:

Users are currently able to enroll in an event multiple times. This results in redundant entries in the MongoDB database. The expected behavior is that once a user has enrolled in an event, subsequent enrollments for the same event by the same user should either be blocked or not allowed.

### Steps to Reproduce:

1. Navigate to the event enrollment page.
2. Enroll in an event.
3. Navigate back to the same event.
4. Attempt to enroll again.

### Expected Behavior:

After the first enrollment, the user should either see a message indicating they've already enrolled or the enrollment button should be disabled/hidden.

### Actual Behavior:

The system allows the user to enroll multiple times, leading to redundant entries in the database.

### Additional Information:

- **Database**: MongoDB
- **Affected Release Version**: 3.0 release of BurnOut
- **Platform**: Web

### Potential Impact:

1. **Data Redundancy**: This could lead to increased storage usage and potential inconsistencies in data.
2. **User Confusion**: Users might be unsure if their first enrollment was successful, leading them to enroll multiple times.

### Suggested Fix:

Implement a check before enrollment to see if a user has already enrolled in the event. If they have, provide appropriate feedback to the user and prevent the redundant enrollment action.

**Comment by amritav** [comment]
Looks like there's no method in place to see if an existing data entry is present.

**Comment by sharonjoji99** [comment]
Lets try creating an API endpoint which check if user has already enrolled or not.

**Comment by amritav** [comment]
Makes sense. Implementing it now.

**Comment by sharonjoji99** [comment]
God speed 🚀
