### ISSUE TITLE
 Implement a Website Footer for Enhanced User Experience

### ISSUE THREAD

**Issue by Diksha-Maurya** [adi-kiran/burnout-healthgoalsapp#45]
### Why do we need this
Footers are vital for trust and legal compliance on a website, providing users with essential information and ensuring a consistent, user-friendly experience.

### Scope of Impact
The footer is available on every page throughout the entire website, ensuring a seamless and cohesive user experience. It should include essential information.

### Points to consider

- The footer's design and content should harmonize with the overall website aesthetics and theme, maintaining a cohesive visual and functional integration that contributes to a seamless user experience. This consistency reinforces the brand identity and ensures that users can easily locate and interact with footer elements, enhancing the website's overall usability.

- Make sure to add license and copyright information.

**Comment by sharonjoji99** [comment]
Are we keeping this simple ? like only limited information ?

**Comment by Diksha-Maurya** [comment]
> Are we keeping this simple ? like only limited information ?

Yeah for now, lets keep license and copyright information.

**Comment by sharonjoji99** [comment]
Sounds good to me @amritav  @adi-kiran  you guys okay with it ?

**Comment by amritav** [comment]
Yeah, works!! Lets keep it simple

**Comment by Diksha-Maurya** [comment]
> Yeah, works!! Lets keep it simple

We have Implemented this issue. Hence closing it
