### ISSUE TITLE
Bug: Event Images Not Rendering on Events Page

### ISSUE THREAD

**Issue by amritav** [adi-kiran/burnout-healthgoalsapp#46]
### Bug Description:

On the Events Page, the images associated with each event are failing to render. Instead of the event image, users are either seeing broken image links or no images at all.

### Steps to Reproduce:

1. Navigate to the Events Page.
2. Browse through the list of events.

### Expected Behavior:

Each event listing should display its associated image.

### Actual Behavior:

Event images are not rendering, showing broken image icons or blank spaces where the image should be.

### Additional Information:

- **Browser/Device**: Microsoft Edge, macOS
- **Affected Version**: BurnOut Release 4

**Comment by amritav** [comment]
@adi-kiran Can you look into this?

**Comment by adi-kiran** [comment]
Fixed in this commit https://github.com/adi-kiran/burnout-healthgoalsapp/commit/1850e8560955c83701d0d973c01f494b6ed2aa35

**Comment by adi-kiran** [comment]
Issue was with the location of the images. Moving it under public fixed it.
