### ISSUE TITLE
Fix hardcoded values in User Profile

### ISSUE THREAD

**Issue by amritav** [adi-kiran/burnout-healthgoalsapp#5]
### Why we need this
The height, weight, and target weight values entered by users is not displaying correctly on the user profile page. Although the data is successfully stored in the database, the code responsible for fetching and displaying user profile information is not dynamically retrieving it from the database; instead, it relies on hardcoded values. 

### Scope of Impact
display_profile.html
application.py

### Implementation
1. **Identify the Hardcoded Values:**
   - Locate the specific parts of the code in `display_profile.html`, `application.py`, and interactions with MongoDB where the height, weight, and target weight values are currently hardcoded.

2. **Connect to the Database:**
   - Ensure that the application is properly connected to the MongoDB database where user profile data is stored.

4. **Retrieve Data Dynamically:**
   - Modify the code in `application.py` responsible for fetching user profile information from the database. Replace hardcoded values with queries that retrieve the data from MongoDB based on the user's unique identifier or relevant key.

5. **Pass Data to HTML Template:**
   - In `application.py`, update the code responsible for rendering the `display_profile.html` template to include the dynamically retrieved user profile data as variables that can be used in the HTML template.

6. **Update HTML Template:**
   - In `display_profile.html`, replace the hardcoded values with placeholders or template variables that correspond to the data we intend to display.

**Comment by sharonjoji99** [comment]
This has been completed as part of https://github.com/adi-kiran/burnout-healthgoalsapp/issues/8
