### ISSUE TITLE
User Profile database entry not updated

### ISSUE THREAD

**Issue by amritav** [adi-kiran/burnout-healthgoalsapp#8]
**Describe the bug**
User Profile database entry is not updated when user profile is updated on the website.

**To Reproduce**
1. Go to 'User Profile'.
2. Add values for Height, Weight, Goal and Target Weight.
4. Click 'Save Profile'.
5. Check if database entry has been updated.

**Expected behavior**

**Screenshots**
![image](https://github.com/adi-kiran/BurnOut-HealthGoalsApp/assets/19224584/45a7a230-19f8-448d-b9e7-1d27b85476d7)
![image](https://github.com/adi-kiran/BurnOut-HealthGoalsApp/assets/19224584/63d363fb-7765-48d9-925f-f16309d100de)
<img width="1430" alt="image" src="https://github.com/adi-kiran/BurnOut-HealthGoalsApp/assets/19224584/165d690d-2308-4b7e-9cbb-82ee21002dbc">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Microsoft Edge

**Comment by sharonjoji99** [comment]
Weird, i didnt know they did this.
I can pick this up

**Comment by amritav** [comment]
Cool, thanks.

**Comment by sharonjoji99** [comment]
<img width="1582" alt="Screenshot 2023-10-18 at 10 22 25 PM" src="https://github.com/adi-kiran/burnout-healthgoalsapp/assets/40449660/97d1257e-ca49-4c25-82b3-a95fe38776e1">

This UI good ? @amritav

**Comment by amritav** [comment]
@sharonjoji99 Looks good. Let us proceed.

**Comment by sharonjoji99** [comment]
Done, it now retrieves data from the database. However, there is an issue when trying to edit and save the data on the UI and will be create a new issues for that : https://github.com/adi-kiran/burnout-healthgoalsapp/issues/41

**Comment by sharonjoji99** [comment]
WIll be closing this
